[project]
name = "qwc-db-auth"
version = "v2024.12.05"
description = "Authentication with User DB"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "Flask~=3.0.0",
    "Werkzeug~=3.0.6",
    "Flask-JWT-Extended~=4.6.0",
    "flask_login~=0.6.3",
    "Flask-WTF~=1.2.1",
    "Flask-Mail2~=1.0.2",
    "Pillow~=10.4.0",
    "psycopg2~=2.9.9",
    "SQLAlchemy~=2.0.29",
    "pyotp~=2.9.0",
    "qrcode~=7.4.2",
    "python-i18n~=0.3.9",
    "email_validator~=2.1.0.post1",
    "qwc-services-core~=1.3.34"
]

[dependency-groups]
dev = [
    "python-dotenv>=1.0.1",
]
